apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-aio
  namespace: nextcloud
  labels:
    app: nextcloud-aio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-aio
  template:
    metadata:
      labels:
        app: nextcloud-aio
    spec:
      containers:
      - name: nextcloud-aio-mastercontainer
        image: ghcr.io/nextcloud-releases/all-in-one:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1G"
            cpu: "1000m"
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: console
        - containerPort: 8443
          name: https
        volumeMounts:
        - name: aio-config
          mountPath: /mnt/docker-aio-config
        - name: nextcloud-data
          mountPath: /var/www/html/data
      volumes:
      - name: aio-config
        persistentVolumeClaim:
          claimName: aio-config-pvc
      - name: nextcloud-data
        persistentVolumeClaim:
          claimName: nextcloud-data-pvc
