apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-aio-ingress
  namespace: nextcloud
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: nextcloud.nikitades.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-aio
            port:
              number: 80
