apiVersion: v1
kind: Secret
metadata:
  name: storagebox-credentials
  namespace: nextcloud
type: Opaque
stringData:
  username: "u527831"
  password: "0relGox7&F*YD@RU!JSIlh8l#EzvxckSjSw9HGMHN$TmawLYR%MN"
